server.port=8081
spring.application.name=KinalRestApplication

# Conection MySql
spring.datasource.url=jdbc:mysql://localhost:3306/DBCleints_in5av?createDatabaseIfNotExist=true
spring.datasource.username=IN5AV
spring.datasource.password=!+admin5av
//spring.datasource.driver.class=com.mysql.jdbc.Driver

# JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true